name = "Crossterm"
uuid = "89a1a94d-67fa-4c27-8677-ab6d33b1ad6c"
authors = ["Dheepak Krishnamurthy"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
