[general]
library_name = "libcrossterm"
output_file_path = "../src/LibCrossterm.jl"
module_name = "LibCrossterm"
jll_pkg_name = "libcrossterm_jll"
extract_c_comment_style = "doxygen"
show_c_function_prototype = true
use_julia_native_enum_type = true
export_symbol_prefixes = ["crossterm_"]
auto_mutability = true
auto_mutability_with_new = false

[codegen]
use_julia_bool = true
use_ccall_macro = true

[codegen.macro]
macro_mode = "aggressive"
